### ISSUE TITLE
Implement Cypress Tests

### ISSUE THREAD

**Issue by bchampp** [sciformal/hour-logger#32]
Implement Cypress Testing for the Frontend. 

# Acceptance Criteria

- [ ] Implement Cypress Project for Hour Logger
- [ ] Migrate Cognito User pool creation to be per environment
- [ ] Create test users in the PR environment
- [ ] Create tickets for future user flows to test

**Comment by 1freitas** [comment]
Hello @bchampp 
Can I help with theses tasks, principally for test creation with cypress?
I don't understand the item _"Migrate Cognito User pool creation to be per environment"_,  can you explain more details?
