### ISSUE TITLE
Make Get Users API sorteable

### ISSUE THREAD

**Issue by bchampp** [sciformal/hour-logger#52]
The `GET /users` API should be sorteable on a specific field. There is some good readings on the API design here - https://www.taniarascia.com/rest-api-sorting-filtering-pagination/#ascending-vs-descending

# Acceptance Criteria
- [ ] Update the `GET /users` to accept sorteable results (e.g. `GET /users?sort_by=first_name&order=asc`)
- [ ] Sort on: Student Number, First Name, Last Name, Hours Completed, Hours Required
- [ ] Unit Tests

**Comment by avalittle** [comment]
export const getAllUsers = async (
  event: APIGatewayProxyEvent,
): Promise<APIGatewayProxyResult> => {
  let params;
  const { query, sortBy, order} = event.queryStringParameters;
  // if (event.queryStringParameters) {
  //   /**
  //    * ? = query exists -> event.queryStringParamters is populated. 
  //    * get /users?sortBy=firstName
  //    * const {query, sortBy} = event.queryStringParameters
  //    * console.log(sortBy) -> firstName
  //    * console.log(query) -> null
  //    * 
  //    * 
  //    * get /users?sortBy=firstName&query=Brent
  //    * console.log(sortBy) -> firstName
  //    * console.log(query) -> Brent
  //    * 
  //    * try to do general query that looks at multiple fields (scans firstname, lastname, student number)
  //    * 
  //    * use a bunch of if statements based on if query, sortBy and order are set.
  //    */
  //   const { query, sortBy, order} = event.queryStringParameters;

  //   params = {
  //     TableName: process.env.userTable,
  //   };
  // } else {
  //   params = {
  //     TableName: process.env.userTable,
  //   };
  // }

    params = {
        TableName: process.env.userTable,
      };

  try {
    
    const users = await DynamoUtilities.scan(params, dynamoDb);
    if(sortBy) {
      users.sort((a,b) => (a.lastName > b.lastName) ? 1 : ((b.lastName > a.lastName) ? -1 : 0));
    }
    return ResponseUtilities.createAPIResponse(users);
  } catch (err) {
    console.log(err);
    return ResponseUtilities.createErrorResponse(err.message, 500);
  }
};
